version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: chustasoft-martentest-api
    container_name: Xelit3.Playground.EventSourcingMarten
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mydatabase;Username=admin;Password=admin"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data: