@Xelit3.Playground.EventSourcingMarten_HostAddress = http://localhost:8080

GET {{Xelit3.Playground.EventSourcingMarten_HostAddress}}/appointment/[Id]
Accept: application/json

###


POST {{Xelit3.Playground.EventSourcingMarten_HostAddress}}/appointment
Content-Type: application/json

{
  "title": "This is the title",
  "description": "TEST Description"
}

###


PUT {{Xelit3.Playground.EventSourcingMarten_HostAddress}}/appointment
Content-Type: application/json

{
  "id": "[Id]",
  "descriptionUpdated": "TEST Description 2"
}

###


PATCH {{Xelit3.Playground.EventSourcingMarten_HostAddress}}/appointment
Content-Type: application/json

{
  "id": "[Id]",
  "statusUpdated": 1
}

###