@BaseAddress = http://localhost:5053

GET {{BaseAddress}}/todos/
Accept: application/json

###

POST {{BaseAddress}}/todo/
Content-Type: application/json

{
  "title": "Test Title",
  "description": "Description of the task" 
}

###

PUT {{BaseAddress}}/todo/
Content-Type: application/json

{
  "id": 3,
  "title": "Test Title updated",
  "description": "Description of the task updated" 
}

###

PATCH {{BaseAddress}}/todo/status
Content-Type: application/json

{
  "id": 3,
  "status": 1  
}

###

DELETE {{BaseAddress}}/todo?id=4
Content-Type: application/json